### ISSUE TITLE
Probable error in simulating bad timestamps

### ISSUE THREAD

**Issue by zawy12** [kyuupichan/difficulty#17]
In emails with degnr8, it sounds like the bad timestamp simulations are not correct, making good code look bad, and bad code look good.

When an honest timestamp follows a dishonest timestamp, the honest timestamp is not simply his solve time plus the bad timestamp.   If a bad timestamp is +5 T's ahead of his actual time, then an honest timestamp following it will be the previous timestamp minus 5 T plus the honest solvetime.  It sounds like the code is just adding the honest miner's solvetime to the bad timestamp to get his timestamp.  

If two bad timestamps are in a row (as will occur if you randonmly assign timestamp errors) it requires more general coding:  It requires a real timestamp beside the assigned ones.  Then each block's real timestamp should be based on the previous real timestamp, then the "public" (block chain) timestamp with the random error for the D calculation can be assigned from that.

after this is fixed, you should get better results from Degnr8's WT if you employ my symmetrical difficulty  limits that are really just limits on the timestamps (shown below) instead of deleting the ones that have apparent negative solve times.
```
# Degnr8 WT difficulty algorithm 
# zawy timestamp limits
# set constants
T=600
N=30
k=N*(N+1)/2 # normalizes the weighted average
X=10 # max hash attacks expected
limit = X^(3/N) # limits effect of timestamp errors w/o slowing response

# begin algorithm 
for  i = -N+1 to 0   (oldest to newest block in the N window)
    weight++
    t += weight * ST[i] / D[i] 
next i  
t = 1 if t < 1
next_D = T * k / t
next_D = D[0]*limit if next_D > D[0]*limit
next_D = D[0]/limit if next_D < D[0]/limit
```

**Comment by kyuupichan** [comment]
Have you read the code?  It's simple and doesn't support your assertion, to the extent I understand it:

https://github.com/kyuupichan/difficulty/blob/master/mining.py#L380-L385

Only 6 lines there; maybe you can point out the error?

**Comment by dgenr8** [comment]
Updated link due to merge this morning

https://github.com/kyuupichan/difficulty/blob/master/mining.py#L374-L379

**Comment by zawy12** [comment]
[I posted here](https://github.com/kyuupichan/difficulty/pull/4#issuecomment-340395224) to describe the problem created by asymmetrically erasing negative timestamps.  wt-144 does not erase negatives like I assumed in that post, but it still seems to have a big problem by changing timestamps.

The line here:
https://github.com/kyuupichan/difficulty/blob/6b17eb630cf62e112dc4e42b2458d44cff25e669/mining.py#L374
indicates that wall time is being done correctly, so the error is not like I thought in my previous post.

I do not see a test of adding a 2-hour forward time to the timestamp, which is where it seems a big problem can occur in wt-144 as the following shows.

Let's say all miners solve every block in 1 T, but one of them assigns a reverse -6 timestamp to the MTP (6 block-times into past).  The sequence of timestamps on blocks ("1"=1x600) will be:

1, 2, -3, 4, 5

The current code will use these solve times:
1, 1, 0, 2, 1

This does not cause a problem.  It is a little better than not doing anything which will result in:

1, 1, -3, 5, 1, 1

This should be worse on only 1 block, causing 3/144 more error on that one block, and mostly immediately erased by the 5 on the next block as soon as it comes into the rolling avg. I don't know how not doing anything would cause the reported 8% error in avg solvetime. Maybe I had a code error someplace else?

But if a miner adds the allowed +12T time to the timestamp (which does not appear to be tested), not doing anything seems better than current code.  Here's the timestamps:

1, 2, 15, 4, 5, 6, 7, 8,....

The current code will use solve times:
1, 1, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,1...

So there's a 12/144 error for a bock that is not taken into corrected until after 13 blocks. For the 1st block after the 13, the difficulty is more than 10% lower. A big miner can then mine as fast as he wants for 13 blocks, quit, and the algorithm never saw any of the high hash rate and only slowly rose back up to normal.  Not doing anything would give something a lot better:

1, 1, 13, -15, 1, 1, 1...

Miners are more likely to add forward timestamps than reverse ones.

**Comment by dgenr8** [comment]
I added a ft100 scenario to test miners setting future times. See https://github.com/kyuupichan/difficulty/pull/19.   The wt-144 mean is elevated to 636.  All algos have 3000+ stddev.  The 144 algos have 25000+ max. and k-1 has 20000 max.

Your no-adjustment algorithm runs without crashing (unlike the +1s scenario) and produces mean 739, stddev 3470, and max block 22000.

**Comment by dgenr8** [comment]
@zawy12 
"A big miner can then mine as fast as he wants for 13 blocks, quit, and the algorithm never saw any of the high hash rate"

A really big miner would produce the approximate sequence
1, 2, 15, 2, 2, 2, 2, 2,....

And there could be a whole lot of zero solve times.  But zero solve times make difficulty rise faster than anything else, so please explain "never saw any of the high hash rate"...

In further testing, in a "ft200" scenario with 200 PH evil hashrate, wt-144 shows max block 34000 but no further ill effects (with the timestamp handling code removed though, the mean goes over 800s).  cw-144 has its _median cut in half_ to 130s and max block goes to 62000.

Notably, k-1 shows no further ill effects at all with ft200.

**Comment by zawy12** [comment]
timestamps: 1,2,15,4,5,6,7,
I get this:
2nd loop: max(15, 2) = 15
time =15-2 =13
3rd loop: max(4,15) = 15
time = 15-15 = 0

so: 1, 15, 0, ....

Yeah, difficulty starts rising after it falls 10%.  But it's only going to rise back to the normal difficulty after 13 blocks if they have 100x hashpower.  With N=30 and allowed negatives, D would be 50x higher in 15 blocks.  I'm going to look into the code to figure out why you'er still getting better results w/o the negatives.  Try taking the MTP error out and compare.

**Comment by dgenr8** [comment]
MTP error?  This future-time test was done independent of the past-time test.

**Comment by kyuupichan** [comment]
@zawy12 The only algo using MTP is k-1.

**Comment by zawy12** [comment]
By MTP error I meant this line that throws in an error on the assigned timestamp, simulating a miner with a slow clock.

https://github.com/kyuupichan/difficulty/blob/6b17eb630cf62e112dc4e42b2458d44cff25e669/mining.py#L377

**Comment by dgenr8** [comment]
@zawy12 Could you add your wt algorithm as an official option in the simulation?  If you don't want to use git you could attach it here as a patch file.

**Comment by zawy12** [comment]
Getting involved more directly in the mining.py is on my list of things to do.  I've worked 6 months in my spreadsheet testing everything under the Sun, so it's a little difficult switching gears.  But I need to start actually programming so people can plug in to what I'm doing. But I like watching the charts as I change variables beside them every second.

**Comment by zawy12** [comment]
I'm closing this because there was nothing wrong with the fake negative timestamps like I thought. I'm opening a new issue to address WT handling of timestamps.
