### ISSUE TITLE
A quick question

### ISSUE THREAD

**Issue by DesWurstes** [kyuupichan/difficulty#18]
https://github.com/kyuupichan/difficulty/blob/cdeee93f9c91fd4cf86afd05bd3aa8248b08af8f/mining.py#L260

I don't understand that line.

Shouldn't it be

    timespan = timespan * 2 // ((block_count) * (block_count + 1)) # Normalize recency weight

because of `n(n+1)/2`?

**Comment by zawy12** [comment]
Two lines below that you can see the missing block_count you're looking for.

**Comment by dgenr8** [comment]
The reason these factors are applied in different steps is because the ``block_count`` factor is necessary even with neutral weights.
