### ISSUE TITLE
wt loop has an error?

### ISSUE THREAD

**Issue by zawy12** [kyuupichan/difficulty#20]
https://github.com/kyuupichan/difficulty/blob/6b17eb630cf62e112dc4e42b2458d44cff25e669/mining.py#L253

The loop seems to be going from 1 to block_count+1.  But it should be from 1 to block_count in order for the n(n+1)/2 to be the correct definition of the average.  I may have had an error also.  For my version for comparison, use this:

```
# constants:  
# N=30
# limit=10^(3/N)
def next_bits_wt(msg, N, limit_precision):
    timespan = 0
    weight=0
    for i in range(-N+1, 0):
         weight++
        tiimespan += (states[i].timestamp - states[i-1].timestamp) *  bits_to_target(states[i].bits) * weight
   target = timespan *2 // 600 // N // N+1
   target_prev= bits_to_target(states[0].bits)
   if target > prev_target*limit: target=prev_target*limit
    if target < prev_target/limit: target=prev_target/limit
   return target_to_bits(target)
```

**Comment by dgenr8** [comment]
I think they both work.  mining.py goes from 1 to (block_count - 1 + 1).

**Comment by zawy12** [comment]
I think your code needs these two changes:
```
  for i in range(first + 2, last + 1):

  timespan += adj_time_i * (i - first-1)
```
I think the "first" and "last" need to be replaced and just use block_count (and replace block_count) with N.  The "first" and "last" are confusing. 

Yours goes from -block_count to 0, which is N+1 instead of N.
