### ISSUE TITLE
Improvement to WT-144 (it's a WWHM) to match Jacob's EMA

### ISSUE THREAD

**Issue by zawy12** [kyuupichan/difficulty#27]
In investigating how and why WT-144 works, I found out it is a weighted harmonic mean (WHM).  This is used instead of the weighted arithmetic mean when the numerator instead of denominator of a rate being measured is known.   

**Take velocity for example.**  Let's say you travel 50 mph for 1 hour and 100 mph for 3 hours. Velocity is distance/time, and we know the time, so we use the **weighted arithmetic mean**:

avg velocity = (50\*1+100\*3)/(1+3) = 87.5 mph.

Now let's say we traveled 50 mph for 50 miles and 100 mph for 300 miles (it's the same thing as above), then we use **weighted harmonic mean**:

avg velocity = (50+300)/(50/50+300/100) = 87.5 mph.

By inverting things you can derive one from the other. They both end up giving you the objective sum(distance) / sum(time) = total distance / total time.

**In our case of looking for average hashrate,** difficulty parallels velocity's distance and solvetime parallels travel time.  The reason we need to use the harmonic mean is because we know difficulty (the numerator), while random chance strongly affects time.  If you look at the equation for WHM you can see the 50/50 and 300/100 give simply travel time (so we need to weight only time, not t/D, as long as we utilize sum(D) at the end).  So, the following should be the more correct calculation of Tom Harold's. This uses the above concepts then injects his method of weighting. If you take out "weight" and k in the following it should be the WHM without the additional weighting devised by Tom (which adjusts for the recent slope of the trend). I am getting better results during simulated hash attacks with this, as well as more stable solvetimes as a result of attacks.  I'm taking out all adjustments for non-sequential solvetimes because as long as bitcoin's +12 and -6 limits are enforced it should be the best thing to do.  

It seems to match the capability of Jacob Eliosoff's exponential moving average (EMA) which seems to be better than WT-144.  I have not posted on the EMA because I'm still trying to understand and improve it. I define one method as better than another if it "gives away" fewer blocks during a 4x hash attack that begins at a D value < avg D and ends at a D value > avg D.  I test them for various beginning and ending D values. I also check to see if median is closer to its correct value of 0.693 of the mean. I do not use std dev of solvetime as a guide (for hash attacks) because it does not seem to be a good measure for protection.

Future work: Combing Tom's and Jacob's methods while making N a continuous function that lowers itself if the statistics indicate the hashrate changing. It will go to a shorter window during a hash-attack and extend to a larger window if hashrate is constant, but in a continuous fashion, not some hit or miss coding with only 2 different windows. I wold like no more than 4 blocks per attack stolen, while keeping a pretty constant difficulty if hashrate is not changing.

It's a weighted-weighted harmonic mean.

```
# WT-144 (modified to be a WWHM) 
#  Tom Harold's (Degnr8's) WT algo
# possibly improved to be a more exact WHM by zawy
# N=144 
# T=600
# k=(N+1)/2         ##### changed
# adjust = 0.998 # for N=144

def next_bits_WMA(N):
    target = 0
    weight=0
    btt=0
    for i in range(-N+1, 0):
        weight++
        st = (states[i].timestamp - states[i-1].timestamp)
        target +=  st * weight                  #### changed
        btt +=bits_to_target(states[i].bits) #### changed
target *= adjust / k / btt                       #### changed
 target_prev= bits_to_target(states[0].bits)
 return target_to_bits(target)
```

**Comment by zawy12** [comment]
To clarify the above:

WT-144 without the weighting is a harmonic mean, but it needs to be a weighted harmonic mean, before Degnr8's weightings are applied. 

Take 3 difficulties with 3 solvetimes.  Let's say D is 1, 2, and 3, with solvetimes are 4,5,6.   Without the weighting of more recent blocks, wt-144 implies this type averaging method as its foundation:

```harmonic_mean_D_per_t =~ 3 / [ 1/(D1/t1) + 1/(D2/t2) + 1/(D3/t3) ] = 0.353```(eq 1)

With the weightings it becomes:

```wt-144_avg_D_per_t=3*(3+1)/2/ [3/ (D1/t1) +2/(D2/t2) +1/(D3/t3) ]=0.316``` (eq 2)

A basic arithmetic mean that is also not correct:

```naive_mean_D_per_t =~ ( D1/t1 + D2/t2 + D3/t3 ) / 3 = 0.383```

A weighted arithmetic mean and weighted harmonic mean turn out to be the same thing: 

```WAM = ( D1/t1*t1 + D2/t2*t2 + D3/t3*t3 ) / (t1+t2+t3) = sum(D) / sum(t) = 0.400```
```WHM = (D1+D2+D3) / [ D1/(D1/t1) +D2/(D2/t2) +D3/(D3/t3)]= sum(D) / sum(t)=0.400```(eq 3)

This is how difficulty (and hashrate) are normally calculated.  In comparing eqs 1, 2, and 3, I get the corrected wt-144 to be:

```WWHM = (D1+D2+D3) * (3+1)/2 / ( 3*t1 +2*t2 +1*t3) = 0.429``` (eq 4)

And it gives results better than wt-144 and  as good as the EMA.  The difference is not near as much as the 0.316 in eq 2 verses 0.429 in eq 4 because the difficulties do not change that much.  If the D's were all the same, then they are the same equation which is why wt-144 works good as it is.

But the EMA has the wrong mean at large N and the WWHM has the wrong mean at small N.  There is something that is better and formally correct.  The WWHM does not take into account the non-normal distribution of the Poisson, having a low median., skewed to shorter solvetimes.

**Comment by dgenr8** [comment]
WWHM goes back to combined difficulty and combined time.  I can't believe this is better than applying each difficulty only to the times measured when it was in effect.

**Comment by zawy12** [comment]
<strike>I have to apply a much larger adjustment factor to WWHM (0.92 instead of 0.99 when N=30) to get the correct avg solvetime time when hashrate is constant, but under 10x attacks, solvetime increases only 1%.</strike> With WT it increases 5%.  WT allows 15% more blocks to be "stolen" when 10x attacks begin on 0.9 of avg D and end on 1.2 avg D.    

I understand your reluctance.  I'm "erasing" details.  But because of the Poisson not being symmetrical about the mean, it can be good to erase details.  For example, avg(D/t) gives terrible results and your method is based avg(t/D) which is why I could not believe it worked.  The difference is that D changes less.  The avg(D/t) with a large-changing t in the denominators causes big problems. The small changing D in your denominator works a lot better, but I believe it is not theoretically as accurate as my modification.

In looking at this more, I see the EMA is still better.

**Comment by dgenr8** [comment]
If you're looking for the right way to combine EMA and WT, try applying the EMA to the quantity time[i] * target[i].

**Comment by zawy12** [comment]
This is not an improvement except in how I measure the success based on simulated hash attacks.  WT-144 averaging treats each solvetime like an independent sample like measuring the avg speed of all the cars in a race. The WHM and WAM methods are like finding the avg speed of a single car after several samples of its speed (either distance based or time based).  We would like to know the avg hashrate, but also want to be able to treat the solvetimes independently if it suddenly changes. So I don't have a theoretical basis for saying one is better than the other.
